### ISSUE TITLE
Create Playwright Bot for Scraping Data from Met Eireann

### ISSUE THREAD

**Issue by oislen** [oislen/IrishClimateDashboard#12]
**Goal**
Create an automated process using Playwright to pull weather data from Met Eireann website

**References**
- https://github.com/oislen/Cat-Classifier/tree/main/webscrapers/playwright
- https://www.met.ie/climate/available-data/historical-data
- https://stackoverflow.com/questions/65285831/playwright-automation-cant-bypass-location-popup
- https://playwright.dev/python/
- https://playwright.dev/python/docs/input
- https://playwright.dev/python/docs/locators
- https://playwright.dev/python/docs/api/class-page
- https://playwright.dev/python/docs/api/class-locator
- https://playwright.dev/python/docs/api/class-browsercontext

**Comment by siam1113** [comment]
Hi @oislen ,
I would love to work this issue of pulling weather data. Let me know if I can work on this.
